### ISSUE TITLE
i3blocks.conf - volume command script

### ISSUE THREAD

**Issue by jackBzzz** [alexbooker/dotfiles#17]
Hello,

My ubuntu 15.10, upgraded to 16.04 machine does not have pulseaudio-ctl available in the repos.

What happened to the volume Perl script [https://www.youtube.com/watch?v=ARKIwOlazKI](url)?
I had an issue with it - my audio sink passed as the first argument is actually 0, which makes the script exit early. I solved it by:
# my $sink=$ARGV[0] || die("Need a sink number as the first argument\n");

if (!defined $ARGV[0]) {die("Need a sink number as the first argument\n");}
my $sink=$ARGV[0];
# continue code

Regards.

**Comment by bookercodes** [comment]
Hi @jackBzzz,

I'll get back to you soon. Thanks.

**Comment by jackBzzz** [comment]
Hi,

Do you think the issue is relevant? Are there any additional info that I can provide?

Regards,
J.

**Comment by bookercodes** [comment]
Sorry for not getting back to you when I said I would :disappointed: 

Whilst I appreciate you taking the time to post I do not see the relevance of this issue as I am not using Ubuntu any more.
