### ISSUE TITLE
How can I install your .dotfiles?

### ISSUE THREAD

**Issue by lucasmoreiradev** [alexbooker/dotfiles#2]
Hey, Alex! How can I install your .dotfiles in my terminal? (.vimrc, .zshrc, etc).

I want to start learning Vim.

 I'm beginner, sorry bro. :expressionless:

**Comment by bookercodes** [comment]
Yo.

Sorry, but my dot files are not _yet_ installable.

**Comment by lucasmoreiradev** [comment]
Oh! No problem! 

Thank you anyway.
