### ISSUE TITLE
Having issues getting rofi theming to work

### ISSUE THREAD

**Issue by Redrield** [alexbooker/dotfiles#24]
I'm following your 2015 guide to rice i3 on youtube, and I've gotten to the part where you rice Rofi. I've copy-pasted the same bit of config from your .i3/config, and the only change I've made is changing the font to Hack 9. No matter that when I launch rofi after reloading, I get a pale beige mess that covers my whole screen and looks disgusting. I can't seem to get a screenshot of it with maim, but just trust me it looks _nothing_ like what is demonstrated in the video. Are there any changes that have been made since 2015 that would break your configuration options?

I'm using Manjaro 17.0.5 running Linux 4.12

**Comment by bookercodes** [comment]
Sorry mate, I'm not sure, not used that setup in a while

**Comment by Redrield** [comment]
Don't worry about it, did some more digging and found that rofi moved to xresources for theming and got rid of all the command flags you passed.
