### ISSUE TITLE
Rxvt Has the Most Hideous Border

### ISSUE THREAD

**Issue by bookercodes** [alexbooker/dotfiles#4]
For some reason, **rxvt** has the most hideous border:

![](https://i.imgur.com/c1Z8Wf8.png)

I made the border green to highlight the problem:

```
Urxvt.bordercolor: #00ff00
```

I have already tried the following settings:

```
URxvt.internalBorder: 0
URxvt.externalBorder: 0
URxvt.borderless: true
```

I also tried running `urxvt -bl` to make sure it wasn't an erorr in my configuration.

**Comment by bookercodes** [comment]
@airblader,

I am finding you .files to be **very** useful as I transition to Arch. 

Might you have encountered this problem before?

**Comment by Airblader** [comment]
@alexbooker Does it have the same problem when you float it? If not, I would assume it's becaue urxvt defines a width / height increment (which is very typical of terminal emulators – they display only text, afterall).

I would suggest not defining your borders through the xrdb settings, but instead through i3. That way you use i3's borders, not the X11 borders.

**Comment by Airblader** [comment]
Sorry, I misread your post. Maybe this is what you're looking for:

https://bbs.archlinux.org/viewtopic.php?id=94992?db=5

It might also be worth setting i3's `client.background #000000` and seeing what happens?

**Comment by bookercodes** [comment]
Many thanks for your prompt response, @Airblader!

I managed to amalgamate all your information to form a solution:

![](https://i.imgur.com/sFL48cd.png)

Here is I ended up doing:
1. I set both **`URxvt*borderColor`** and **`URxvt*borderColor`** to **`0`**. This removed all all borders **except** the bottom one.
2. I then set **`URxvt*borderColor`**  to the same colour as the **shell** background.
